#!/usr/bin/env python3
"""Build patched LZDoom 4.14.4 and bundle its runtime files for this platform."""
from __future__ import annotations

import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[2]
PREPARE = PROJECT / "native/tools/prepare_lzdoom.py"
SOURCE = PROJECT / "native/work/lzdoom-l4.14.4"
DEPS = PROJECT / "native/deps"
ZMUSIC_SOURCE = DEPS / "zmusic-1.1.14"
ZMUSIC_BUILD = DEPS / "build-zmusic"
ZMUSIC_PREFIX = DEPS / "install-zmusic"
ZMUSIC_REPOSITORY = "https://github.com/ZDoom/ZMusic.git"
ZMUSIC_TAG = "1.1.14"


def platform_id() -> str:
    system = platform.system().lower()
    machine = platform.machine().lower()
    architecture = "arm64" if machine in {"arm64", "aarch64"} else "x86_64"
    os_id = "windows" if system == "windows" else ("macos" if system == "darwin" else "linux")
    return f"{os_id}-{architecture}"


def run(command: list[str], cwd: Path | None = None) -> None:
    print("+", " ".join(command))
    subprocess.run(command, cwd=cwd, check=True)


def ensure_zmusic(generator: str) -> None:
    DEPS.mkdir(parents=True, exist_ok=True)

    if ZMUSIC_SOURCE.is_dir():
        try:
            current_tag = subprocess.check_output(
                ["git", "-C", str(ZMUSIC_SOURCE), "describe", "--tags", "--exact-match"],
                text=True,
                stderr=subprocess.DEVNULL,
            ).strip()
        except (subprocess.CalledProcessError, FileNotFoundError):
            current_tag = ""

        if current_tag != ZMUSIC_TAG:
            print(
                f"Removing incompatible ZMusic source: "
                f"{current_tag or 'unknown'}; expected {ZMUSIC_TAG}"
            )
            shutil.rmtree(ZMUSIC_SOURCE)

    if not ZMUSIC_SOURCE.is_dir():
        run([
            "git", "clone",
            "--depth", "1",
            "--branch", ZMUSIC_TAG,
            ZMUSIC_REPOSITORY,
            str(ZMUSIC_SOURCE),
        ])

    header = ZMUSIC_SOURCE / "include/zmusic.h"
    if not header.is_file():
        raise SystemExit(f"ZMusic header not found: {header}")

    header_text = header.read_text(encoding="utf-8", errors="replace")
    required_symbol = "zmusic_mod_preferredplayer"
    if required_symbol not in header_text:
        raise SystemExit(
            f"ZMusic {ZMUSIC_TAG} does not expose required symbol: "
            f"{required_symbol}"
        )

    ZMUSIC_BUILD.mkdir(parents=True, exist_ok=True)
    ZMUSIC_PREFIX.mkdir(parents=True, exist_ok=True)

    configure = [
        "cmake", "-S", str(ZMUSIC_SOURCE), "-B", str(ZMUSIC_BUILD),
        "-G", generator,
        "-DCMAKE_BUILD_TYPE=Release",
        f"-DCMAKE_INSTALL_PREFIX={ZMUSIC_PREFIX}",
    ]
    configure.extend(
        filter(
            None,
            os.environ.get("DOOMCRAFT_ZMUSIC_CMAKE_ARGS", "").split(";"),
        )
    )

    run(configure)
    run([
        "cmake", "--build", str(ZMUSIC_BUILD),
        "--config", "Release",
        "--parallel",
    ])
    run([
        "cmake", "--install", str(ZMUSIC_BUILD),
        "--config", "Release",
    ])

    installed_header = ZMUSIC_PREFIX / "include/zmusic.h"
    if not installed_header.is_file():
        raise SystemExit(
            f"Installed ZMusic header not found: {installed_header}"
        )

    installed_text = installed_header.read_text(
        encoding="utf-8",
        errors="replace",
    )
    if required_symbol not in installed_text:
        raise SystemExit(
            f"Installed ZMusic header does not expose: {required_symbol}"
        )


def copy_runtime(executable: Path, build: Path, destination: Path, pid: str) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for old in destination.iterdir():
        if old.name != ".gitkeep":
            if old.is_dir(): shutil.rmtree(old)
            else: old.unlink()

    target_name = "lzdoom.exe" if pid.startswith("windows") else "lzdoom"
    copied: list[str] = []

    def copy_file(source: Path, relative: str | None = None) -> None:
        relative = relative or source.name
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, target)
        if target.name == target_name and not pid.startswith("windows"):
            target.chmod(0o755)
        normalized = target.relative_to(destination).as_posix()
        if normalized not in copied: copied.append(normalized)

    copy_file(executable, target_name)

    # Engine data generated by LZDoom's build (lzdoom.pk3, game_support.pk3, etc.).
    for suffix in ("*.pk3", "*.dat"):
        for asset in sorted(build.rglob(suffix)):
            if asset.is_file(): copy_file(asset)

    # LZDoom requires its default SoundFont and FM banks at runtime.
    # CMake generates these beside the executable, but they must also be
    # preserved inside the mod JAR using their relative directories.
    resource_sources = (
        (executable.parent / "soundfonts", "soundfonts"),
        (build / "soundfonts", "soundfonts"),
        (SOURCE / "soundfont", "soundfonts"),
        (executable.parent / "fm_banks", "fm_banks"),
        (build / "fm_banks", "fm_banks"),
        (SOURCE / "fm_banks", "fm_banks"),
    )

    copied_resources: set[str] = set()

    for source_directory, destination_directory in resource_sources:
        if not source_directory.is_dir():
            continue

        for resource in sorted(source_directory.rglob("*")):
            if not resource.is_file() or resource.stat().st_size <= 0:
                continue

            relative = (
                Path(destination_directory)
                / resource.relative_to(source_directory)
            ).as_posix()

            if relative in copied_resources:
                continue

            copy_file(resource, relative)
            copied_resources.add(relative)

    required_runtime_resources = (
        destination / "soundfonts/lzdoom.sf2",
        destination / "fm_banks/GENMIDI.GS.wopl",
        destination / "fm_banks/gs-by-papiezak-and-sneakernets.wopn",
    )

    missing_runtime_resources = [
        str(resource)
        for resource in required_runtime_resources
        if not resource.is_file() or resource.stat().st_size <= 0
    ]

    if missing_runtime_resources:
        raise SystemExit(
            "Missing required LZDoom runtime resource(s): "
            + ", ".join(missing_runtime_resources)
        )

    # Runtime libraries, especially ZMusic.
    library_patterns = ["*.dll", "*.dylib", "*.so", "*.so.*"]
    for base in (executable.parent, ZMUSIC_PREFIX):
        for pattern in library_patterns:
            for library in sorted(base.rglob(pattern)):
                if library.is_file() and library.stat().st_size > 0:
                    copy_file(library, library.name)

    (destination / "native-manifest.txt").write_text("\n".join(sorted(copied)) + "\n", encoding="utf-8")
    print(f"Bundled {len(copied)} native runtime files in {destination}")


def main() -> None:
    run([sys.executable, str(PREPARE)])
    pid = platform_id()
    build = PROJECT / "native/build" / pid
    destination = PROJECT / "src/main/resources/natives" / pid
    build.mkdir(parents=True, exist_ok=True)
    generator = os.environ.get("DOOMCRAFT_CMAKE_GENERATOR", "Ninja")

    if os.environ.get("DOOMCRAFT_SKIP_ZMUSIC", "0") != "1":
        ensure_zmusic(generator)

    cmake_args = [
        "cmake", "-S", str(SOURCE), "-B", str(build),
        "-G", generator,
        "-DCMAKE_BUILD_TYPE=Release",
        f"-DCMAKE_PREFIX_PATH={ZMUSIC_PREFIX}",
    ]
    cmake_args.extend(filter(None, os.environ.get("DOOMCRAFT_CMAKE_ARGS", "").split(";")))
    run(cmake_args)
    run(["cmake", "--build", str(build), "--config", "Release", "--parallel"])

    candidates: list[Path] = []
    for name in ("lzdoom", "lzdoom.exe", "zdoom", "zdoom.exe"):
        candidates.extend(path for path in build.rglob(name) if path.is_file())
    if not candidates:
        raise SystemExit(f"No LZDoom executable found below {build}")

    executable = max(candidates, key=lambda path: path.stat().st_size)
    copy_runtime(executable, build, destination, pid)


if __name__ == "__main__":
    main()
